### ISSUE TITLE
로그인 시 502 Bad Gateway 오류

### ISSUE THREAD

**Issue by scarf005** [exciting-transcendence/transcendence#77]
# 개요
![_03](https://user-images.githubusercontent.com/54838975/184288877-b8b926a1-7712-41fc-877e-b12f1641128c.png)
![_04](https://user-images.githubusercontent.com/54838975/184296740-9225b8ec-5a97-4dd9-9aef-828d2060bcfc.png)

## 재현 방법
- `localstorage,` `sessionstorage` 전부 초기화

```sh
docker system prune -a
./dc.sh dev build
./dc.sh dev up
```
### nginx 설정
```sh
❯ ./dc.sh dev exec reverse_proxy /bin/ash
/ # cd /etc/nginx/conf.d/
/etc/nginx/conf.d # cat default.conf 
server {
  listen 3000;

  location / {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_pass http://frontend:3000;
  }

  location /api {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_pass http://backend:3000;
  }

  location /socket.io {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_pass http://backend:3000;
  }
}
```
### Docker Compose 로그
```js
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:29 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OAGj4JV HTTP/1.1" 200 118 "http://localhost:3000/ws-api" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:29 +0000] "POST /socket.io/?EIO=4&transport=polling&t=OAGj4Jn&sid=PCQzqDUWeNtPt8aOAAAA HTTP/1.1" 200 2 "http://localhost:3000/ws-api" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-backend-1        | chat: new connection
transcendence-backend-1        | 
transcendence-backend-1        | /app/node_modules/jsonwebtoken/verify.js:53
transcendence-backend-1        |     return done(new JsonWebTokenError('jwt must be provided'));
transcendence-backend-1        |                 ^
transcendence-backend-1        | JsonWebTokenError: jwt must be provided
transcendence-backend-1        |     at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:53:17)
transcendence-backend-1        |     at JwtService.verify (/app/node_modules/@nestjs/jwt/dist/jwt.service.js:38:20)
transcendence-backend-1        |     at UserService.getUidFromToken (/app/src/user/user.service.ts:139:37)
transcendence-backend-1        |     at ChatGateway.handleConnection (/app/src/chat/chat.gateway.ts:33:40)
transcendence-backend-1        |     at Object.next (/app/node_modules/@nestjs/websockets/web-sockets-controller.js:71:47)
transcendence-backend-1        |     at ConsumerObserver.next (/app/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
transcendence-backend-1        |     at SafeSubscriber.Subscriber._next (/app/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
transcendence-backend-1        |     at SafeSubscriber.Subscriber.next (/app/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
transcendence-backend-1        |     at /app/node_modules/rxjs/src/internal/operators/distinctUntilChanged.ts:173:22
transcendence-backend-1        |     at OperatorSubscriber._this._next (/app/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
transcendence-reverse_proxy-1  | 2022/08/12 06:18:29 [error] 10#10: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.20.0.1, server: , request: "GET /socket.io/?EIO=4&transport=websocket&sid=PCQzqDUWeNtPt8aOAAAA HTTP/1.1", upstream: "http://172.20.0.4:3000/socket.io/?EIO=4&transport=websocket&sid=PCQzqDUWeNtPt8aOAAAA", host: "localhost:3000"
transcendence-reverse_proxy-1  | 2022/08/12 06:18:29 [error] 9#9: *7 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.20.0.1, server: , request: "GET /socket.io/?EIO=4&transport=polling&t=OAGj4Jn.0&sid=PCQzqDUWeNtPt8aOAAAA HTTP/1.1", upstream: "http://172.20.0.4:3000/socket.io/?EIO=4&transport=polling&t=OAGj4Jn.0&sid=PCQzqDUWeNtPt8aOAAAA", host: "localhost:3000", referrer: "http://localhost:3000/ws-api"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:29 +0000] "GET /socket.io/?EIO=4&transport=websocket&sid=PCQzqDUWeNtPt8aOAAAA HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:29 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OAGj4Jn.0&sid=PCQzqDUWeNtPt8aOAAAA HTTP/1.1" 502 157 "http://localhost:3000/ws-api" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:30 +0000] "GET /api HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 2022/08/12 06:18:30 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /api HTTP/1.1", upstream: "http://172.20.0.4:3000/api", host: "localhost:3000"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:30 +0000] "POST /socket.io/?EIO=4&transport=polling&t=OAGj4aX&sid=PCQzqDUWeNtPt8aOAAAA HTTP/1.1" 502 157 "http://localhost:3000/ws-api" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 2022/08/12 06:18:30 [error] 9#9: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "POST /socket.io/?EIO=4&transport=polling&t=OAGj4aX&sid=PCQzqDUWeNtPt8aOAAAA HTTP/1.1", upstream: "http://172.20.0.4:3000/socket.io/?EIO=4&transport=polling&t=OAGj4aX&sid=PCQzqDUWeNtPt8aOAAAA", host: "localhost:3000", referrer: "http://localhost:3000/ws-api"
transcendence-reverse_proxy-1  | 2022/08/12 06:18:30 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /api HTTP/1.1", upstream: "http://172.20.0.4:3000/api", host: "localhost:3000"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:30 +0000] "GET /api HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 2022/08/12 06:18:31 [error] 9#9: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /socket.io/?EIO=4&transport=polling&t=OAGj4qI HTTP/1.1", upstream: "http://172.20.0.4:3000/socket.io/?EIO=4&transport=polling&t=OAGj4qI", host: "localhost:3000", referrer: "http://localhost:3000/ws-api"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:31 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OAGj4qI HTTP/1.1" 502 157 "http://localhost:3000/ws-api" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 2022/08/12 06:18:34 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /socket.io/?EIO=4&transport=polling&t=OAGj5Sv HTTP/1.1", upstream: "http://172.20.0.4:3000/socket.io/?EIO=4&transport=polling&t=OAGj5Sv", host: "localhost:3000", referrer: "http://localhost:3000/ws-api"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:34 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OAGj5Sv HTTP/1.1" 502 157 "http://localhost:3000/ws-api" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
transcendence-reverse_proxy-1  | 2022/08/12 06:18:38 [error] 9#9: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /socket.io/?EIO=4&transport=polling&t=OAGj6a9 HTTP/1.1", upstream: "http://172.20.0.4:3000/socket.io/?EIO=4&transport=polling&t=OAGj6a9", host: "localhost:3000", referrer: "http://localhost:3000/ws-api"
transcendence-reverse_proxy-1  | 172.20.0.1 - - [12/Aug/2022:06:18:38 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OAGj6a9 HTTP/1.1" 502 157 "http://localhost:3000/ws-api" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0" "-"
```

**Comment by hoikii** [comment]
소켓 연결시 전달받은 토큰이 없을 때 백이 죽어버리는 문제였습니다.
PR # 75가 임시로 문제를 해결하고는 있지만 유효하지 않은 토큰이 들어왔을 땐 같은 문제가 생길 것으로 예상됩니다.
